#!/bin/bash

if [ -n "$BASH_SOURCE" ]; then
	THIS_FILE=${BASH_SOURCE}
elif [ -n "$ZSH_NAME" ]; then
	THIS_FILE=${0}
else
	THIS_FILE=$0
fi
THIS_DIR=$(dirname $THIS_FILE)
WSROOT=$(realpath $THIS_DIR)

if [ ! -f $WSROOT/.build ]; then
	echo "Build config has not yet been set up." >&2
	echo "Please run '8dev-setup-build' to set up build config." >&2
	return 1
fi

read BUILD_DIR < $WSROOT/.build
read CONFIG_NAME < $WSROOT/.config

if [ ! -d $BUILD_DIR ]; then
	echo "Build directory '$BUILD_DIR' is not initialised." >&2
	echo "Please run '8dev-setup-build' to set up the build." >&2
	return 1
fi

echo "Initialising build environment for '$CONFIG_NAME' @ $BUILD_DIR"

# Propagate workspace root directory path
BB_ENV_PASSTHROUGH_ADDITIONS="$BB_ENV_PASSTHROUGH_ADDITIONS WSROOT"
export BB_ENV_PASSTHROUGH_ADDITIONS WSROOT

. $BUILD_DIR/init-build-env
